sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t adeshina100/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true adeshina100/docker-react npm run test
